services:
  employee:
    image: animapolis/employee
    container_name: employee
    ports:
      - "8011:8011"
    environment:
      SPRING_PROFILE_ACTIVE: "dev"
      SPRING_CONFIG_IMPORT: "configserver:http://config:8099/"
      SPRING_CLOUD_STEAM_KAFKA_BINDER_BROKERS: "kafka:9092"
    extends:
      file: docker-compose.base.yml
      service: base_service

  healthcare:
    image: animapolis/healthcare
    container_name: healthcare
    ports:
      - "8012:8012"
    environment:
      SPRING_PROFILE_ACTIVE: "dev"
      SPRING_CONFIG_IMPORT: "configserver:http://config:8099/"
      SPRING_CLOUD_STEAM_KAFKA_BINDER_BROKERS: "kafka:9092"
    extends:
      file: docker-compose.base.yml
      service: base_service

  config:
    image: animapolis/config
    container_name: config
    ports:
      - "8099:8099"
    depends_on:
      - kafka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8099/actuator/health/readiness" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    extends:
      file: docker-compose.base.yml
      service: base_all

  postgres:
    image: postgres:18.6-alpine3.24
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: animapass123!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./dev/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
    extends:
      file: docker-compose.base.yml
      service: base_all

  kafka:
    image: 'apache/kafka:4.3.1'
    container_name: kafka
    ports:
      - '9092:9092'
    extends:
      file: docker-compose.base.yml
      service: base_all
networks:
  animapolis_network:
volumes:
  postgres_data: