# Spring
spring.cloud.stream.kafka.binder.brokers=localhost:9092
management.endpoints.web.exposure.include=info,health,refresh,busrefresh

# Server
server.port=8011

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password={cipher}cc34b24d274e23198b265cd0964012c2ccfb38e57053c763d397124173180634
spring.h2.console.enabled=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.registry-fetch-interval-seconds=30
eureka.instance.prefer-ip-address=true
eureka.instance.lease-expiration-duration-in-seconds=10
# Logging
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO
