# Spring
spring.mvc.problemdetails.enabled=true

# Server
server.port=8012

# Database
spring.datasource.url=jdbc:h2:file:./healthcare_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password={cipher}1486fb15ddb6e2d96353db8f8171ada2b2b53b81458044e93e18897186e8116b0d5a55777fb3b6455f30be76d77be477
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE