# Spring
spring.application.name=configserver
spring.mvc.problemdetails.enabled=true

# Spring Cloud
spring.cloud.config.server.git.uri=https://github.com/${CONFIG_GIT_USERNAME}/Animapolis.git
spring.cloud.config.server.git.username=${CONFIG_GIT_USERNAME}
spring.cloud.config.server.git.password=${CONFIG_GIT_TOKEN}
spring.cloud.config.server.git.default-label=config
spring.cloud.config.server.git.timeout=5
spring.cloud.config.server.git.clone-on-start=true

# Server
server.port=8099
encrypt.key=${CONFIG_ENCRYPT_KEY}

# Logging
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE